---
title: "Tipos de datos y estructuras en R"
author: '@jrcajide'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tipos de datos básicos en R

```{r eval=FALSE}
# Esto es un comentario
"a"
2
TRUE
```

### Funciones

* c()
* length()  ¿Qué longitud tiene?
* class()  ¿De qué tipo es?
* paste()
* seq()
* sum()


**Ejemplo:**
```{r}
x <- "hola!"
class(x)

y <- 1:10
class(y)
length(y)

z <- c(1, 2, 3)
class(z)


```

**Cargando nuevas funciones**

```{r}
# install.packages("stringr")
library(stringr)
str_length(x)
str_to_upper(x)
str_to_title(x)
```


**Creando nuestras funciones**

```{r}
suma <- function(a, b) {
  
  respuesta <- a + b

  return (respuesta)
}

suma(3, 6)

# Afortunadamente :)

sum(3,6)
```


## Estructuras de datos

#### Vectores

```{r}

dispositivos <- c('Mobile', 'Tablet')
print(dispositivos) 
mas.dispositivos <- c(dispositivos, 'Desktop')
print(mas.dispositivos)

# Indexing
dispositivo_tablet <- dispositivos[2]
print(dispositivo_tablet)

dispositivos <- c('Mobile', 'Tablet', 'Desktop')
todos.menos.tablet <- dispositivos[-2]  
dispositivos[c(2, 3)]

indices <- c(2, 3)
dispositivos[indices]

navegadores <- c('Chrome', 'Safari', 'Explorer', 'Firefox', 'Lynx', 'Opera')
navegadores[2:5]


tamano.pantallas <- c(7, 6.5, 4, 11, 8)
tamano.pantallas[c(TRUE, FALSE, FALSE, TRUE, TRUE)]

pantalla.es.grande <- tamano.pantallas > 6.5
pantallas.grandes <- tamano.pantallas[ pantalla.es.grande ] 

tamano.pantallas[tamano.pantallas > 6.5] 

# Modificando un vector
medios <- c('', 'Buscadores', 'Mail')
medios[3] <- 'Email'
medios[c(1,2)] <- c('Directo', 'Organic')

# Operaciones vectorizadas

v1 <- c(1, 1, 1, 1, 1)
v2 <- c(1, 2, 3, 4, 5)

v1 + v2  
v1 - v2  
v1 * v2  
v1 / v2

v3 <- v1 + v1 

v4 <- (v1 + v2) / v3


```

### Matrices

```{r}
m <- matrix(nrow = 2, ncol = 2)
m
dim(m)

# Se rellenan por columnas
m <- matrix(1:6, nrow = 2, ncol = 3)
m

# Otras formas de construir matrices
x <- 1:3
y <- 10:12
(cbind(x, y))

# ó
(rbind(x, y))

```

### Listas

```{r}
# Se crean con list()
x <- list(1, "a", TRUE)
x
```

**Ejemplo:**
```{r}
xlist <- list(a = "Conjunto de datos iris", b = 1:10, data = head(iris))
xlist
xlist$b
```

### Factores

```{r}
sexo <- factor(c("masculino", "femenino", "femenino", "masculino"))
levels(sexo)
nlevels(sexo)
length(levels(sexo))

# Orden de los factores
tallas <- factor(c("s", "xl", "m", "xl", "s", "m", "xl"))
levels(tallas)

```
**¿Podemos saber cuál es la talla más pequeña?**
```{r eval=FALSE}
min(tallas)
```

```{r}
tallas <- factor(tallas, levels=c("s", "m", "xl"), ordered = TRUE)
levels(tallas)
min(tallas) ## Ahora sí

```

**Muy útil: Tabla de contingencia**
```{r}
table(tallas)
```

### Dataframes
```{r}
df <- data.frame(id = letters[1:10], x = 1:10, y = rnorm(10))
df
# agregar nuevas variables
cbind(df, data.frame(z = 4))
```

**Funciones útiles:**
```{r eval=FALSE}
head()
tail()
dim()
nrow()
ncol()
str()
names()
```


**Subset**

```{r}
df <-
  data.frame(
    month = month.name[1:12],
    sesiones = round(rnorm(12, mean = 400, sd = 10), 2),
    transacciones = round(rnorm(12, mean = 20, sd = 4), 2)
  )
str(df)

df[df$sesiones < 400, ]
df[c(1, 3), ]

df[, c("month", "transacciones")]
# df[c("month", "transacciones")]


```
